# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev1+g57fd47a.d20230524'
__version_tuple__ = version_tuple = (0, 1, 'dev1', 'g57fd47a.d20230524')
